"""init

Revision ID: cc5f8d4955a0
Revises: 
Create Date: 2026-09-23 13:12:09.403933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5f8d4955a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b24_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b24_jobs_done'), 'b24_jobs', ['done'], unique=False)
    op.create_table('b24_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_domain', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('application_token', sa.Text(), nullable=False),
    sa.Column('contacts_watermark', sa.DateTime(), nullable=True),
    sa.Column('deals_watermark', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_domain')
    )
    op.create_table('b24_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b24_contact_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('assigned_b24_user_id', sa.Integer(), nullable=False),
    sa.Column('has_active_deal', sa.Boolean(), nullable=False),
    sa.Column('last_deal_at', sa.DateTime(), nullable=True),
    sa.Column('last_deal_amount', sa.Float(), nullable=False),
    sa.Column('last_deal_title', sa.String(length=255), nullable=False),
    sa.Column('deals_count', sa.Integer(), nullable=False),
    sa.Column('consent_source', sa.String(length=255), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_b24_contact_id'), 'contacts', ['b24_contact_id'], unique=True)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dns_status', sa.String(length=16), nullable=False),
    sa.Column('warmup_started_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('incoming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('in_reply_to', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('body_snippet', sa.Text(), nullable=False),
    sa.Column('classified_by', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('b24_comment_id', sa.Integer(), nullable=True),
    sa.Column('is_ndr', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_classification'), 'incoming', ['classification'], unique=False)
    op.create_index(op.f('ix_incoming_in_reply_to'), 'incoming', ['in_reply_to'], unique=False)
    op.create_index(op.f('ix_incoming_message_id'), 'incoming', ['message_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_processed_event')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(length=255), nullable=False),
    sa.Column('smtp_pass', sa.String(length=255), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_user', sa.String(length=255), nullable=False),
    sa.Column('imap_pass', sa.String(length=255), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.String(length=10), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('suppression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_email'), 'suppression', ['email'], unique=True)
    op.create_table('verification_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_runs_email'), 'verification_runs', ['email'], unique=False)
    op.create_table('worker_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('is_advertising', sa.Boolean(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_contact_id'), 'consents', ['contact_id'], unique=False)
    op.create_table('warmup_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('next_send_at', sa.DateTime(), nullable=True),
    sa.Column('ooo_until', sa.DateTime(), nullable=True),
    sa.Column('paused_reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_enrollment')
    )
    op.create_index(op.f('ix_enrollments_campaign_id'), 'enrollments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_enrollments_contact_id'), 'enrollments', ['contact_id'], unique=False)
    op.create_index(op.f('ix_enrollments_next_send_at'), 'enrollments', ['next_send_at'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_table('sequence_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('subject_tpl', sa.Text(), nullable=False),
    sa.Column('body_tpl', sa.Text(), nullable=False),
    sa.Column('threaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_steps_campaign_id'), 'sequence_steps', ['campaign_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('step_pos', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('smtp_error', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('b24_activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_enrollment_id'), 'messages', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_enrollment_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sequence_steps_campaign_id'), table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_next_send_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_contact_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_campaign_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_table('warmup_tasks')
    op.drop_index(op.f('ix_consents_contact_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('campaigns')
    op.drop_table('worker_heartbeat')
    op.drop_index(op.f('ix_verification_runs_email'), table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_suppression_email'), table_name='suppression')
    op.drop_table('suppression')
    op.drop_table('senders')
    op.drop_table('segments')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_incoming_message_id'), table_name='incoming')
    op.drop_index(op.f('ix_incoming_in_reply_to'), table_name='incoming')
    op.drop_index(op.f('ix_incoming_classification'), table_name='incoming')
    op.drop_table('incoming')
    op.drop_table('domains')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_b24_contact_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('b24_users')
    op.drop_table('b24_state')
    op.drop_index(op.f('ix_b24_jobs_done'), table_name='b24_jobs')
    op.drop_table('b24_jobs')
    # ### end Alembic commands ###
